Add missing includes for std::istream.
This fixes the following link errors:

../json/libjsoncpp.a(json_reader.cpp.o): In function `Json::Reader::parse(std::__1::basic_istream<char, std::__1::char_traits<char> >&, Json::Value&, bool)':
/var/tmp/usr/ports/net-p2p/eiskaltdcpp-daemon/work/eiskaltdcpp-2.2.10/json/jsoncpp/src/json_reader.cpp:(.text+0x3d7): undefined reference to `std::__1::basic_istream<char, std::__1::char_traits<char> >& std::__1::getline<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_istream<char, std::__1::char_t  its<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, char)'
c++: error: linker command failed with exit code 1 (use -v to see invocation)